
export let COMPANY_NAME:string = "";

export const prompt:string = `
Let's write a sizzling website copy wireframe for COMPANY_NAME, an COMPANY_ONE_LINER.
I am a world-class UX-focused copywriter. We are writing the wireframes in a google docs app running from sidebar iframe. 
- and I am using sharing feedback from founder as well as some info.

TASK:
You will help me write modern, concise, never banal UX copy that resonates with audiences and follows modern UX and copywriting practice.

NOTES:
- HTML: pseudocode generated by a google docs script, as I'm writing in a google docs wireframing app for writers. Ready?

Here is work so far. Help me improve it.
`
